# Generated by Django 4.1.4 on 2022-12-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegapp', '0004_remove_encodemodel_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encodemodel',
            name='coverimage',
        ),
        migrations.AddField(
            model_name='encodemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
