# Generated by Django 4.1.4 on 2022-12-30 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stegapp', '0005_remove_encodemodel_coverimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='decodemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.CharField(max_length=1000, null=True)),
                ('key10', models.CharField(max_length=1000, null=True)),
                ('key20', models.CharField(max_length=1000, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_image/CoverImage/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
