# Generated by Django 4.1.4 on 2022-12-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegapp', '0006_decodemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decodemodel',
            old_name='ciphertext',
            new_name='key3',
        ),
        migrations.RenameField(
            model_name='decodemodel',
            old_name='key10',
            new_name='key4',
        ),
        migrations.RemoveField(
            model_name='decodemodel',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='decodemodel',
            name='key20',
        ),
        migrations.RemoveField(
            model_name='encodemodel',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='decodemodel',
            name='stegoimage',
            field=models.ImageField(blank=True, null=True, upload_to='stegoimage/StegoImage/'),
        ),
        migrations.AddField(
            model_name='encodemodel',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='coverimage/CoverImage/'),
        ),
    ]
