# Generated by Django 4.1.4 on 2022-12-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegapp', '0007_rename_ciphertext_decodemodel_key3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encodemodel',
            name='encryptype',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
