# Generated by Django 4.1.4 on 2022-12-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegapp', '0008_encodemodel_encryptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='decodemodel',
            name='decryptype',
            field=models.CharField(choices=[('Vigenere Cipher', 'Vigenere Cipher'), ('Beaufort Cipher', 'Beaufort Cipher'), ('Bifid Cipher', 'Bifid Cipher')], default='Vigenere Cipher', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encodemodel',
            name='encryptype',
            field=models.CharField(choices=[('Vigenère Cipher', 'Vigenère Cipher'), ('Beaufort Cipher', 'Beaufort Cipher'), ('Bifid Cipher', 'Bifid Cipher')], default='Vigenere Cipher', max_length=1000),
        ),
    ]
