# Generated by Django 4.1.4 on 2022-12-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegapp', '0009_decodemodel_decryptype_alter_encodemodel_encryptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decodemodel',
            name='decryptype',
            field=models.CharField(choices=[('Vigenère Cipher', 'Vigenère Cipher'), ('Beaufort Cipher', 'Beaufort Cipher'), ('Bifid Cipher', 'Bifid Cipher')], default='Vigenere Cipher', max_length=1000),
        ),
    ]
