# Generated by Django 4.1.4 on 2023-01-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegapp', '0010_alter_decodemodel_decryptype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decodemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='encodemodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='decodemodel',
            name='decryptype',
            field=models.CharField(choices=[('Vigenère Cipher', 'Vigenère Cipher'), ('Beaufort Cipher', 'Beaufort Cipher')], default='Vigenère Cipher', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encodemodel',
            name='encryptype',
            field=models.CharField(choices=[('Vigenère Cipher', 'Vigenère Cipher'), ('Beaufort Cipher', 'Beaufort Cipher')], default='Vigenère Cipher', max_length=1000),
        ),
    ]
