# Generated by Django 4.1.7 on 2023-03-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegapp', '0012_alter_encodemodel_encryptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decodemodel',
            name='decryptype',
            field=models.CharField(choices=[('Vigenère Cipher', 'Vigenère Cipher'), ('Beaufort Cipher', 'Beaufort Cipher'), ('Autokey Cipher', 'Autokey Cipher'), ('Porta Cipher', 'Porta Cipher')], default='Vigenère Cipher', max_length=1000),
        ),
    ]
