# Generated by Django 4.1.7 on 2023-03-18 01:54

from django.db import migrations, models
import stegapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('stegapp', '0014_alter_decodemodel_decryptype_alter_decodemodel_key3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decodemodel',
            name='decryptype',
            field=models.CharField(choices=[('Vigenère Cipher', 'Vigenère Cipher'), ('Beaufort Cipher', 'Beaufort Cipher'), ('Autokey Cipher', 'Autokey Cipher'), ('Porta Cipher', 'Porta Cipher')], default='Vigenère Cipher', max_length=500),
        ),
        migrations.AlterField(
            model_name='decodemodel',
            name='key3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='decodemodel',
            name='key4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='decodemodel',
            name='stegoimage',
            field=models.ImageField(blank=True, null=True, upload_to=stegapp.models.get_stego_image_path),
        ),
        migrations.AlterField(
            model_name='encodemodel',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to=stegapp.models.get_cover_image_path),
        ),
        migrations.AlterField(
            model_name='encodemodel',
            name='encryptype',
            field=models.CharField(choices=[('Vigenère Cipher', 'Vigenère Cipher'), ('Beaufort Cipher', 'Beaufort Cipher'), ('Autokey Cipher', 'Autokey Cipher'), ('Porta Cipher', 'Porta Cipher')], default='Vigenère Cipher', max_length=500),
        ),
        migrations.AlterField(
            model_name='encodemodel',
            name='key1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encodemodel',
            name='key2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encodemodel',
            name='plaintext',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
